/*
 *
 * Copyright (c) 2006-2020, Speedment, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); You may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.speedment.common.function;

/**
 * A function that takes an object and returns a primitive {@code short}.
 * <p>
 * Generated by com.speedment.sources.pattern.function.ToFunctionPattern
 * 
 * @param <T> argument type
 * 
 * @author Emil Forslund
 * @since  1.0.2
 */
@FunctionalInterface
public interface ToShortFunction<T> {
    
    /**
     * Applies this function to the given argument.
     * 
     * @param value the argument
     * @return      the result
     */
    short applyAsShort(T value);
}