/**
 * The different types of predicates generated by Fields are located in this
 * package. The main difference between a Speedment predicate and an ordinary
 * java predicate is that Speedment predicates also carry metadata about the
 * Field and other conditions used to create it. This metadata can be parsed to
 * produce smarter queries runtime.
 * <p>
 * This package is part of the API. Modifications to classes here should only
 * (if ever) be done in major releases.
 */
package com.speedment.runtime.field.predicate;
